name: sample Git Actions
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello, world!"

  windows:
    needs: [ubuntu]
    runs-on: windows-latest
    steps:
    - run: echo "Hello, world!"

